name: publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"
      - name: Install build
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cilantro-web
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  docs-publish:
    name: Publish documentation
    steps:
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
